### ISSUE TITLE
Undefined variable: banner in /theme/contemporary/lib.php on line 185

### ISSUE THREAD

**Issue by thepurpleblob** [3ilogiclms/moodle-theme_contemporary#1]
Function references the variable $banner in lib.php but it doesn't exist. Throws hundreds of notices with debugging switched on.

**Comment by 3ilogiclms** [comment]
Hi
Thanks for using contemporary theme, we shall look into the matter & get back to you.

Regards,
3i Logic LMS Team

**Comment by 3ilogiclms** [comment]
Hi,

The problem has been resolved now you can update lib.php file. Thanks again for raising this issue

Best Regards,
3i Logic LMS Team
