### ISSUE TITLE
Image for theme too large

### ISSUE THREAD

**Issue by ConstanceHorne** [3ilogiclms/moodle-theme_contemporary#2]
The Contemporary theme has such a large example photo that the "auto-sizing" of the table for selecting a theme has made the area too large to be displayed and no horizontal scroll bar comes up so there was no way to get to the button to switch themes. 

Even stretching my browser across two large monitors did not allow the "Select" button to appear. 

I had to kick the theme out of the theme directory and purge the cache (again). Then the selection button re-appears.

This is a really ugly kludge and obviously will not work in a production environment.

Please make the image example smaller so that you can switch between themes without manual intervention.

FYI - Testing on my WAMP stack with Win 7 and v2.8.3.

**Comment by 3ilogiclms** [comment]
Dear ConstanceHorne,

Thanks for raising this issue, Our LMS developers have resolved this issue and latest version of Contemporary will be uploaded at Moodle community within next month 

Regards,
3i Logic LMS Team.

**Comment by 3ilogiclms** [comment]
Dear ConstanceHonre,

Latest version of Contemporary them has been uploaded and we've resolved image sizing issue as you raised.

Thanks & Best Regards,
3i Logic LMS Team
