### ISSUE TITLE
Navigation Block: line break after icon when text ist too long

### ISSUE THREAD

**Issue by HonkXL** [3ilogiclms/moodle-theme_contemporary#6]
I have some content that has a long text in the title. In the navigation there is an useless line break after the icon.
I think this looks bad. It would be better without this line break. I marked the problem in red on the screenshot.

![moodle-contemp](https://user-images.githubusercontent.com/16715040/28766560-6d94054c-75d0-11e7-92f3-530471b1e81f.png)

**Comment by HonkXL** [comment]
Same problem in the settings:

![moodle-layout](https://user-images.githubusercontent.com/16715040/28818350-2782546a-76ab-11e7-8bec-09eb136d8e1b.jpg)

PHP 7.1.7, Moodle 3.3.1 Build 20170710, Theme: 3.3 - 2017051500

**Comment by 3ilogiclms** [comment]
Dear HonKXL,

Our development team has been fixed layout and alignment issues of contemporary theme. We've updated it on Contemporary development branch and it will be updated on Moodle probably on next week. Thank you again for raising the issue. If you have any further comments please feel free to give your valuable input.

Thank you,
3i Logic LMS Team

**Comment by HonkXL** [comment]
Great - this works now. I will close this issue. Thank you!
