### ISSUE TITLE
Layout - text overlapped by elements

### ISSUE THREAD

**Issue by HonkXL** [3ilogiclms/moodle-theme_contemporary#7]
There are a lot of points, where the text is overlapped by elements.

In the feedback-settings:

<img width="372" alt="overlapping1" src="https://user-images.githubusercontent.com/16715040/28798234-2bf5c14c-7644-11e7-9e66-533dd87f144d.png">

Or in the questions:

<img width="272" alt="overlapping2" src="https://user-images.githubusercontent.com/16715040/28798254-3a9c08f0-7644-11e7-9792-5a4c17708ee5.png">

<img width="484" alt="overlapping3" src="https://user-images.githubusercontent.com/16715040/28798266-40dc5832-7644-11e7-84ad-ad3462cc955c.png">

**Comment by 3ilogiclms** [comment]
Dear Thomas,

Thank you for raising the issue. Just confirm about Moodle version, PHP version and theme version that you are using. We'll look into this and resolve the problems.

Thank you,
3i Logic LMS Team

**Comment by HonkXL** [comment]
Thank you!

PHP 7.1.7, Moodle 3.3.1 Build 20170710, Theme: 3.3 - 2017051500

Just found some more problems, like this one when logging in with a wrong password (see screenshot).
I tested with latest Firefox on Windows and latest Safari on MacOSX Sierra. Same problem on both systems.

![login](https://user-images.githubusercontent.com/16715040/28817874-cfca17e0-76a9-11e7-8fee-6fb8a06b1c6b.jpg)

**Comment by HonkXL** [comment]
Great - looks much better now! I will close this issue!
